name: Build Qt 5.15

on:
  workflow_dispatch:

env:
  qt_version: 5.15.14
  openssl_version: 3.3.1

jobs:
  Build_x64:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Download Qt ${{ env.qt_version }} sources
        run: .\download_sources.cmd repack ${{ env.qt_version }} ${{ env.openssl_version }}

      - name: Upload patched Qt ${{ env.qt_version }} sources
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Qt ${{ env.qt_version }} patched src
          path: |
            src_archive/*
          compression-level: 9
          retention-days: 5

      - name: Install Qt jom
        run: .\install_jom.cmd

      - name: Build Qt ${{ env.qt_version }} x64
        run: .\build_sources.cmd x64 ${{ env.qt_version }}

      - name: Upload built Qt ${{ env.qt_version }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Qt ${{ env.qt_version }} x64
          path: |
            archive/*
          compression-level: 0

      - name: Upload built OpenSSL ${{ env.openssl_version }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: OpenSSL ${{ env.qt_version }} x64
          path: |
            openssl-win64/bin/*.dll
            openssl-win64/bin/*.exe
            openssl-win64/bin/*.pdb
          compression-level: 9

  Build_x86:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Download Qt ${{ env.qt_version }} sources
        run: .\download_sources.cmd no_repack ${{ env.qt_version }} ${{ env.openssl_version }}

      - name: Install Qt jom
        run: .\install_jom.cmd

      - name: Build Qt ${{ env.qt_version }} x86
        run: .\build_sources.cmd Win32 ${{ env.qt_version }}

      - name: Upload built Qt
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Qt ${{ env.qt_version }} x86
          path: |
            archive/*
          compression-level: 0

      - name: Upload built OpenSSL ${{ env.openssl_version }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: OpenSSL ${{ env.qt_version }} x86
          path: |
            openssl-win32/bin/*.dll
            openssl-win32/bin/*.exe
            openssl-win32/bin/*.pdb
          compression-level: 9
